
CREATE DATABASE IF NOT EXISTS `mekashronstartajob`;
USE `mekashronstartajob`;

CREATE TABLE IF NOT EXISTS `entities` (
  `entityID` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  `CategoryID` INTEGER DEFAULT 0,
  `CreatedBy` INTEGER DEFAULT 0,
  `EntityCreatedDate` TEXT DEFAULT NULL,
  `EntityLastUpdateDate` NUMERIC DEFAULT NULL,
  `FirstName` TEXT DEFAULT NULL,
  `LastName` TEXT DEFAULT NULL,
  `Company` TEXT DEFAULT NULL,
  `Address` TEXT DEFAULT NULL,
  `City` TEXT DEFAULT NULL,
  `State` TEXT DEFAULT NULL,
  `Country` TEXT DEFAULT NULL,
  `Zip` TEXT DEFAULT NULL,
  `Phone` TEXT DEFAULT NULL,
  `AllowPhone` INTEGER NOT NULL DEFAULT 1,
  `Mobile` TEXT DEFAULT NULL,
  `Mobile_isWhatsApp` INTEGER NOT NULL DEFAULT 0,
  `mobile_verified` INTEGER DEFAULT 0,
  `mobile_verification_code` TEXT DEFAULT NULL,
  `AllowMobile` INTEGER NOT NULL DEFAULT 1,
  `Fax` TEXT DEFAULT NULL,
  `fax_verified` INTEGER DEFAULT 0,
  `AllowFax` INTEGER DEFAULT 1,
  `Email` TEXT DEFAULT NULL,
  `email_verified` INTEGER DEFAULT 0,
  `AllowEmail` INTEGER NOT NULL DEFAULT 1,
  `profile_imageID` INTEGER NOT NULL DEFAULT 1,
  `SharedUsers` TEXT DEFAULT NULL,
  `isChecked` TEXT DEFAULT NULL,
  `CryptedID` INTEGER DEFAULT 0,
  `isDeleted` INTEGER NOT NULL DEFAULT 0,
  `MergedID` INTEGER DEFAULT NULL,
  `DeletedDate` NUMERIC DEFAULT NULL,
  `DeletedBy` INTEGER DEFAULT 0,
  `CustomAction6` NUMERIC DEFAULT NULL,
  `CustomField1` TEXT DEFAULT '',
  `CustomField2` TEXT DEFAULT '',
  `CustomField3` NUMERIC DEFAULT '2013-07-23 22:53:34',
  `CustomField4` NUMERIC DEFAULT '2013-07-23 22:53:34',
  `CustomField5` INTEGER DEFAULT 0,
  `CustomField6` INTEGER DEFAULT 0,
  `CustomField7` INTEGER DEFAULT 0,
  `CustomField8` TEXT,
  `CustomField9` TEXT DEFAULT '',
  `CustomField10` TEXT DEFAULT '',
  `CustomField34` TEXT DEFAULT '',
  `CustomField38` TEXT,
  `CustomField39` INTEGER DEFAULT 0,
  `CountryID` INTEGER DEFAULT NULL,
  `isSupplier` INTEGER DEFAULT 0,
  `isUser` INTEGER DEFAULT 0,
  `isCustomer` INTEGER DEFAULT 0,
  `CustomField46` TEXT,
  `CustomField50` TEXT DEFAULT '',
  `CustomField40` TEXT DEFAULT '',
  `CustomField53` TEXT,
  `isWhatsAPP` INTEGER DEFAULT 0,
  `isBusiness` INTEGER DEFAULT 0,
  `ol_username` TEXT DEFAULT NULL,
  `ol_password` TEXT DEFAULT NULL,
  `CustomField82` NUMERIC DEFAULT NULL,
  `CustomField84` REAL DEFAULT 0,
  `CustomField85` INTEGER DEFAULT 0,
  `CustomField86` INTEGER DEFAULT 0,
  `CustomField88` TEXT DEFAULT '',
  `CustomField89` TEXT DEFAULT '',
  `CustomField90` TEXT DEFAULT '',
  `CustomField91` TEXT DEFAULT '',
  `CustomField92` TEXT DEFAULT '',
  `CustomField94` date DEFAULT NULL,
  `CustomField95` REAL DEFAULT 0,
  `CustomField105` TEXT DEFAULT '',
  `CustomField106` TEXT DEFAULT '',
  `CustomField107` TEXT DEFAULT '',
  `CustomField108` TEXT DEFAULT '',
  `CustomField109` TEXT DEFAULT '',
  `CustomField111` INTEGER DEFAULT NULL,
  `CustomField112` INTEGER DEFAULT NULL,
  `CustomField113` INTEGER DEFAULT 0,
  `CustomField114` REAL DEFAULT 0,
  `CustomField115` REAL DEFAULT 1,
  `CustomField116` REAL DEFAULT 0.1,
  `CustomField122` REAL DEFAULT 0,
  `CustomField123` REAL DEFAULT 0,
  `CustomField124` REAL DEFAULT 0,
  `CustomField125` REAL DEFAULT 0,
  `CustomField126` TEXT DEFAULT '',
  `CustomField127` INTEGER DEFAULT 0,
  `CustomField128` REAL DEFAULT 0,
  `CustomField129` TEXT DEFAULT '',
  `CustomField130` INTEGER DEFAULT 0,
  `CustomField137` INTEGER DEFAULT '1',
  `CustomField138` INTEGER DEFAULT '1',
  `CustomField139` INTEGER DEFAULT '1',
  `CustomField140` INTEGER DEFAULT '1',
  `CustomField141` INTEGER DEFAULT '1',
  `CustomField142` INTEGER DEFAULT '1',
  `CustomField143` INTEGER DEFAULT '1',
  `CustomField144` INTEGER DEFAULT '1',
  `CustomField145` INTEGER DEFAULT '1',
  `CustomField146` INTEGER DEFAULT '1',
  `CustomField149` TEXT DEFAULT '',
  `CustomField150` TEXT,
  `CustomField155` TEXT,
  `CustomField156` TEXT DEFAULT 'en',
  `CustomField177` REAL DEFAULT 0,
  `CustomField178` INTEGER DEFAULT 0,
  `CustomField179` INTEGER DEFAULT 0,
  `CustomField181` REAL DEFAULT 0,
  `CustomField183` REAL DEFAULT 0,
  `CustomField185` TEXT DEFAULT '',
  `CustomField187` INTEGER DEFAULT 0,
  `CustomField188` REAL DEFAULT 0,
  `CustomField189` REAL DEFAULT 0,
  `CustomField192` REAL DEFAULT 0,
  `CustomField195` REAL DEFAULT 0,
  `CustomField196` REAL DEFAULT 0,
  `CustomField201` INTEGER DEFAULT 0,
  `CustomField214` INTEGER DEFAULT 0,
  `CustomField215` TEXT DEFAULT '',
  `CustomField218` INTEGER DEFAULT 0,
  `CustomField219` REAL DEFAULT 0,
  `CustomField220` TEXT DEFAULT '',
  `CustomField221` REAL DEFAULT 0,
  `CustomField223` REAL DEFAULT 0
);