-- --------------------------------------------------------
-- Host:                         5.79.66.76
-- Server version:               5.6.23-log - MySQL Community Server (GPL)
-- Server OS:                    Win64
-- HeidiSQL Version:             10.2.0.5599
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Dumping database structure for mekashronstartajob
CREATE DATABASE IF NOT EXISTS `mekashronstartajob` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `mekashronstartajob`;

-- Dumping structure for table mekashronstartajob.entities
CREATE TABLE IF NOT EXISTS `entities` (
  `entityID` int(20) unsigned NOT NULL AUTO_INCREMENT,
  `CategoryID` smallint(6) unsigned DEFAULT '0',
  `CreatedBy` smallint(5) unsigned DEFAULT '0',
  `EntityCreatedDate` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `EntityLastUpdateDate` datetime DEFAULT NULL,
  `FirstName` varchar(255) DEFAULT NULL,
  `LastName` varchar(255) DEFAULT NULL,
  `Company` varchar(255) DEFAULT NULL,
  `Address` varchar(255) DEFAULT NULL,
  `City` varchar(255) DEFAULT NULL,
  `State` varchar(255) DEFAULT NULL,
  `Country` varchar(255) DEFAULT NULL,
  `Zip` varchar(255) DEFAULT NULL,
  `Phone` varchar(40) DEFAULT NULL,
  `AllowPhone` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `Mobile` varchar(40) DEFAULT NULL,
  `Mobile_isWhatsApp` tinyint(4) NOT NULL DEFAULT '0',
  `mobile_verified` tinyint(3) unsigned DEFAULT '0',
  `mobile_verification_code` varchar(8) DEFAULT NULL,
  `AllowMobile` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `Fax` varchar(50) DEFAULT NULL,
  `fax_verified` tinyint(3) unsigned DEFAULT '0',
  `AllowFax` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `Email` varchar(165) DEFAULT NULL,
  `email_verified` tinyint(3) unsigned DEFAULT '0',
  `AllowEmail` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `profile_imageID` int(11) NOT NULL DEFAULT '0',
  `SharedUsers` varbinary(255) DEFAULT NULL,
  `isChecked` varbinary(255) DEFAULT NULL,
  `CryptedID` int(100) unsigned DEFAULT '0',
  `isDeleted` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `MergedID` int(11) unsigned DEFAULT NULL,
  `DeletedDate` datetime DEFAULT NULL,
  `DeletedBy` int(20) unsigned DEFAULT '0',
  `CustomAction6` datetime DEFAULT NULL,
  `CustomField1` varbinary(255) DEFAULT '',
  `CustomField2` varbinary(255) DEFAULT '',
  `CustomField3` datetime DEFAULT '2013-07-23 22:53:34',
  `CustomField4` datetime DEFAULT '2013-07-23 22:53:34',
  `CustomField5` tinyint(1) DEFAULT '0',
  `CustomField6` tinyint(1) DEFAULT '0',
  `CustomField7` int(20) unsigned DEFAULT '0',
  `CustomField8` text,
  `CustomField9` varbinary(255) DEFAULT '',
  `CustomField10` varbinary(255) DEFAULT '',
  `CustomField34` varbinary(255) DEFAULT '',
  `CustomField38` text,
  `CustomField39` tinyint(1) DEFAULT '0',
  `CountryID` smallint(5) unsigned DEFAULT NULL,
  `isSupplier` tinyint(1) unsigned DEFAULT '0',
  `isUser` tinyint(1) unsigned DEFAULT '0',
  `isCustomer` tinyint(1) unsigned DEFAULT '0',
  `CustomField46` text,
  `CustomField50` varbinary(512) DEFAULT '',
  `CustomField40` varchar(512) DEFAULT '',
  `CustomField53` text,
  `isWhatsAPP` tinyint(1) unsigned DEFAULT '0',
  `isBusiness` tinyint(1) unsigned DEFAULT '0',
  `ol_username` varchar(64) DEFAULT NULL,
  `ol_password` varchar(64) DEFAULT NULL,
  `CustomField82` date DEFAULT NULL,
  `CustomField84` double DEFAULT '0',
  `CustomField85` tinyint(1) DEFAULT '0',
  `CustomField86` tinyint(1) DEFAULT '0',
  `CustomField88` varchar(512) DEFAULT '',
  `CustomField89` varchar(512) DEFAULT '',
  `CustomField90` varchar(512) DEFAULT '',
  `CustomField91` varchar(512) DEFAULT '',
  `CustomField92` varchar(512) DEFAULT '',
  `CustomField94` date DEFAULT NULL,
  `CustomField95` double DEFAULT '0',
  `CustomField105` varchar(512) DEFAULT '',
  `CustomField106` varchar(512) DEFAULT '',
  `CustomField107` varchar(512) DEFAULT '',
  `CustomField108` varchar(512) DEFAULT '',
  `CustomField109` varchar(512) DEFAULT '',
  `CustomField111` int(20) unsigned DEFAULT NULL,
  `CustomField112` int(20) unsigned DEFAULT NULL,
  `CustomField113` tinyint(1) DEFAULT '0',
  `CustomField114` double DEFAULT '0',
  `CustomField115` double DEFAULT '1',
  `CustomField116` double DEFAULT '0.1',
  `CustomField122` double DEFAULT '0',
  `CustomField123` double DEFAULT '0',
  `CustomField124` double DEFAULT '0',
  `CustomField125` double DEFAULT '0',
  `CustomField126` varchar(512) DEFAULT '',
  `CustomField127` tinyint(1) DEFAULT '0',
  `CustomField128` double DEFAULT '0',
  `CustomField129` varchar(512) DEFAULT '',
  `CustomField130` tinyint(1) DEFAULT '0',
  `CustomField137` tinyint(1) DEFAULT '1',
  `CustomField138` tinyint(1) DEFAULT '1',
  `CustomField139` tinyint(1) DEFAULT '1',
  `CustomField140` tinyint(1) DEFAULT '1',
  `CustomField141` tinyint(1) DEFAULT '1',
  `CustomField142` tinyint(1) DEFAULT '1',
  `CustomField143` tinyint(1) DEFAULT '1',
  `CustomField144` tinyint(1) DEFAULT '1',
  `CustomField145` tinyint(1) DEFAULT '1',
  `CustomField146` tinyint(1) DEFAULT '1',
  `CustomField149` varchar(512) DEFAULT '',
  `CustomField150` text,
  `CustomField155` text,
  `CustomField156` varchar(512) DEFAULT 'en',
  `CustomField177` double DEFAULT '0',
  `CustomField178` tinyint(1) DEFAULT '0',
  `CustomField179` tinyint(1) DEFAULT '0',
  `CustomField181` double DEFAULT '0',
  `CustomField183` double DEFAULT '0',
  `CustomField185` varchar(512) DEFAULT '',
  `CustomField187` tinyint(1) DEFAULT '0',
  `CustomField188` double DEFAULT '0',
  `CustomField189` double DEFAULT '0',
  `CustomField192` double DEFAULT '0',
  `CustomField195` double DEFAULT '0',
  `CustomField196` double DEFAULT '0',
  `CustomField201` tinyint(1) DEFAULT '0',
  `CustomField214` tinyint(1) DEFAULT '0',
  `CustomField215` varchar(512) DEFAULT '',
  `CustomField218` tinyint(1) DEFAULT '0',
  `CustomField219` double DEFAULT '0',
  `CustomField220` varchar(512) DEFAULT '',
  `CustomField221` double DEFAULT '0',
  `CustomField223` double DEFAULT '0',
  PRIMARY KEY (`entityID`),
  KEY `CategoryID` (`CategoryID`),
  KEY `SharedUsers` (`SharedUsers`),
  KEY `Fax` (`Fax`),
  KEY `Email` (`Email`),
  KEY `Phone` (`Phone`),
  KEY `Mobile` (`Mobile`),
  KEY `CustomAction6` (`CustomAction6`),
  KEY `isDeleted` (`isDeleted`),
  KEY `CustomField140` (`CustomField140`),
  KEY `CustomField139` (`CustomField139`),
  KEY `CustomField123` (`CustomField123`),
  KEY `CustomField122` (`CustomField122`),
  KEY `CustomField6` (`CustomField6`),
  KEY `CustomField1` (`CustomField1`),
  KEY `CustomField2` (`CustomField2`),
  KEY `CustomField218` (`CustomField218`),
  KEY `mobile_verified` (`mobile_verified`),
  KEY `fax_verified` (`fax_verified`),
  KEY `isUser` (`isUser`),
  KEY `isCustomer` (`isCustomer`),
  KEY `isBusiness` (`isBusiness`),
  KEY `isSupplier` (`isSupplier`),
  KEY `email__verified` (`email_verified`),
  KEY `ol_username` (`ol_username`),
  KEY `ol_password` (`ol_password`)
) ENGINE=MyISAM AUTO_INCREMENT=138372 DEFAULT CHARSET=utf8;

-- Data exporting was unselected.

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
